### ISSUE TITLE
Translate from floating toolbar after text selection

### ISSUE THREAD

**Issue by Donkey-Doug** [Bnyro/TranslateYou#11]
### Describe your suggested feature

When users select text in android, a floating toolbar appears with options such as copy, paste, cut etc.

Please add an option for "translate" to the floating window. An open source app with this functionality is deepl (https://github.com/sakusaku3939/DeepLAndroid). This is an open source front end to a closed source translation service called deepl.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ilithy** [comment]
I am for adding this feature if possible.
Another, very close (but complementary) is the addition of support for the native android content sharing function, because some apps (when selecting text) inhibits the display of buttons from other apps in this floating text toolbar, except native buttons, like the "Share" button)

https://developer.android.com/training/sharing/send

**Comment by Bnyro** [comment]
Agree, that's the next point on my todo-list :) My week has been busy so I didn't really have time to work on it yet but in theory it shouldn't be hard, in the worst case I'm gonna act as a copy monkey ^)

**Comment by Bnyro** [comment]
Well, I've never been working on something like that and it seems to he a harder task. Please feel free to open a new issue for it, however I can't promise to be looking at it in the next time.
