### ISSUE TITLE
Offline Database?

### ISSUE THREAD

**Issue by PassionateG1t** [Bnyro/TranslateYou#18]
### Describe your suggested feature

I'm not sure about uts feasibility, but is offline usage possible? I haven't yet seen any FOSS app that gives you the ability to download languages for offline use.

### Other details

Currently, I use Google Translate solely because of this feature. The day when we see this in FOSS translate apps will be revolutionary.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The problem with it is that there are no open source packages or libraries that contain a library of words or translations. The only one I found is [Argos Translate](https://github.com/argosopentech/argos-translate) that is used by LibreTranslate which provides a python library.
Unfortunately there's no way to use the python library for Android apps since Android apps can only be build with Java/Kotlin or C/C++, but Python is not supported.

**Comment by Douile** [comment]
Recently added apertium has an example offline translations app using their engine: https://github.com/apertium/apertium-android (although it looks like it hasn't been updated in a few years)
