### ISSUE TITLE
[Bug] Different frames size when "Norwegian" is selected

### ISSUE THREAD

**Issue by serrq** [Bnyro/TranslateYou#227]
I am not sure this is a bug. Might it be enhanced? Both frames with big size by default?

OnePlus CPH2399
Android 13
TY 5.0 Fdroid
Translate provider: My Memory

![1000009292](https://user-images.githubusercontent.com/113377431/232688338-82a730cd-509f-4ea3-b7f9-b59a3264bbca.jpg)

**Comment by HotarunIchijou** [comment]
I have the same resolution with your on my new phone and a bit lower screen size and I don't have problems with Norwegian. But on my old phone there was the same bug with the Norwegian language. I guess that this bug is due to the small size of language frames, as you said, and also because of the flexible frames size

Here's an example of long-named languages. It looks pretty bad, I guess 
![](https://user-images.githubusercontent.com/113282550/233769900-88137929-0b33-48fa-8481-a42352b0dbc0.png)

In Google translate there are no similar things because of the big and fixed language names frames and fine-formatted text
![](https://user-images.githubusercontent.com/113282550/233770184-7cdf52d8-1455-422d-b092-81371cec18f2.png)
