### ISSUE TITLE
tts & stt

### ISSUE THREAD

**Issue by andsofine** [Bnyro/TranslateYou#43]
### Describe your suggested feature

it would be great if translate you could use text to speech and speech to text if they are installed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sure, I can work on that.
I'm not sure how good the Android libraries for it actually are, we'll see it in the end :joy:

**Comment by Bnyro** [comment]
Note: It doesn't work on ROMs like LineageOS and probably others too.

**Comment by Ilithy** [comment]
Sorry to intervene so late on this request, but there is an open source and offline api that can be used to perform stt, it is the [Vosk api (on github)](https://github.com/alphacep/vosk-api) ([website](https://alphacephei.com/vosk/)
Normally able to run without Google's stt engine (like on my pixel 6 pro running grapheneos, which doesn't have Google, like many other roms)

I'm not sure this is usable in TY, but at least the info is passed around, in case it helps

**Comment by Bnyro** [comment]
I agree that Google's stt isn't a really good solution, I actually haven't even tested it since I don't use any Google services on my phone either (luckily nobody complained about it yet x) ).

What concerns me about it is that part: `Portable per-language models are only 50Mb each, but there are much bigger server models available.`. This would mean TY would require 50+ MB (currently 1.5MB) as apk and when installed about 100MB.
I don't think this would be a really good idea to be honest as 
1. Izzy limited his repo to 30MB per app
2. The approach of the app is to stay lightweight

So in the end I think it'd be better to just don't support it on phones that don't have G-services installed.

**Comment by OkyDooky** [comment]
Just took a glance at it and it looks like it can be installed as a service for Android? I could be wrong, but if that is correct, then the user could install it separately from this app and the most that could be included is a written suggestion and link to Vosk.

**Comment by Bnyro** [comment]
> Just took a glance at it and it looks like it can be installed as a service for Android? I could be wrong, but if that is correct, then the user could install it separately from this app and the most that could be included is a written suggestion and link to Vosk.
>
I couldn't find anything about it, however, I will consider it if anyone can lead me to any docs or info about it!
